# pythonScript2.py

import sys
import os

generated_content=""

def main():
    if len(sys.argv) != 4:
        sys.exit(1)

    input_file_path = sys.argv[1]  # Use the input file provided by the first script
    output_file_path = sys.argv[2]
    original_file_name = sys.argv[3]

    # Read the content generated by the first script
    with open(input_file_path, 'r') as input_file:
        generated_content = input_file.read()

    # Add "line 3" to the generated content
    new_content = generated_content + "\nTHIS IS THE SECOND LINE THAT IS BEING ADDED"

    # Write the updated content to the output file
    with open(output_file_path, 'w') as output_file:
        output_file.write(new_content)

    try:
        # Check if the file exists before attempting to delete it
        if os.path.exists(input_file_path):
            os.remove(input_file_path)
        else:
            print(f"File '{input_file_path}' does not exist.")
    except Exception as e:
        print(f"Error deleting the file: {e}")

if __name__ == "__main__":
    main()
